title: arianna@root-logs:~$
description: Documenting the path to root, one log at a time
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
url: "https://lagamma-arianna.github.io/root-logs/"
include:
  - assets/css/custom.css
